"""The deployment pack (spec 8.4, ADR-0021, ADR-0027): OpenTofu for AWS, Azure and GCP, as containers or serverless,
generated by code from the approved design and the target, validated in the sandbox without cloud credentials, with the
fitness functions of the pack computed by code. Its verdict (`iac-<cloud>`) is evidence, like any other: it does not
deploy anything."""

import json
from collections.abc import Callable, Mapping
from typing import Any

from nexti_core.spec.design import Design
from nexti_pack_iac import aws, azure, gcp
from nexti_pack_iac.common import Target, readme, target_of, unsupported
from nexti_pack_iac.fitness import checks as fitness_checks
from nexti_sandbox import Limits, Sandbox
from nexti_verification.verdict import IAC_CHECKS, Check, Verdict, compute

IMAGE = "nexti-sandbox-iac:2"
LIMITS = Limits(cpus=1.0, memory_mb=1024, pids=256, timeout_seconds=300, work_mb=64)
PREFIX = "infra/"
SCRIPT = (
    "cp -r /input/infra /work/infra && cd /work/infra && "
    "tofu init -backend=false -input=false -no-color > /work/init.log 2>&1 || { echo '===INIT-FAILED==='; "
    "cat /work/init.log; exit 2; }; echo '===VALIDATE==='; tofu validate -json -no-color"
)
GENERATORS: dict[str, Callable[[Target], dict[str, str]]] = {"aws": aws.files, "azure": azure.files, "gcp": gcp.files}


def generate(design: Design, target: Mapping[str, Any]) -> dict[str, str]:
    """The IaC files under infra/<cloud>/, empty when the target's cloud has no generator or does not support its
    database (`unsupported` says why)."""
    found = target_of(design, target)
    if found is None:
        return {}
    files = GENERATORS[found.cloud](found)
    files["README.md"] = readme(found)
    return {f"{PREFIX}{found.cloud}/{path}": content for path, content in files.items()}


async def validate(sandbox: Sandbox, files: Mapping[str, str]) -> Check:
    """`tofu init` with the providers of the image and `tofu validate`, in the sandbox, without network."""
    inputs = {f"infra/{path.split('/', 2)[2]}": content.encode("utf-8") for path, content in files.items()
              if path.endswith(".tf")}  # fmt: skip
    result = await sandbox.run(["sh", "-c", SCRIPT], inputs, LIMITS)
    if "===INIT-FAILED===" in result.stdout:
        return Check("validates", "failed", "tofu init failed: " + result.stdout.split("===INIT-FAILED===", 1)[1][:800])
    raw = result.stdout.split("===VALIDATE===", 1)[-1]
    try:
        report = json.loads(raw[raw.find("{") :])
    except json.JSONDecodeError:
        return Check("validates", "failed", f"tofu validate did not answer: {(result.stderr or raw)[-800:]}")
    if report.get("valid"):
        return Check("validates", "passed", f"tofu validate: valid, {report.get('warning_count', 0)} warning(s)")
    errors = [f"{d.get('summary')}: {d.get('detail', '')}"[:200] for d in report.get("diagnostics", [])
              if d.get("severity") == "error"]  # fmt: skip
    return Check("validates", "failed", f"{len(errors)} error(s): {'; '.join(errors[:4])}"[:1000], {"errors": errors})


async def verdict(sandbox: Sandbox, files: Mapping[str, str], cloud: str) -> Verdict:
    """The IaC's own verdict: it validates and meets the fitness functions of the pack."""
    hcl = "\n".join(content for path, content in sorted(files.items()) if path.endswith(".tf"))
    found = [await validate(sandbox, files), *fitness_checks(hcl)]
    not_proven = ["Validated without cloud credentials: what only a plan or a deployment shows (quotas, names "
                  "already taken, permissions of the account) is not checked"]  # fmt: skip
    return compute(f"iac-{cloud}", found, not_proven, required=IAC_CHECKS)


__all__ = ["IMAGE", "PREFIX", "Target", "generate", "target_of", "unsupported", "validate", "verdict"]
