"""What the IaC is generated from (spec 8.4, ADR-0021): the bounded context of the design, the target's cloud and
database, and the legacy concepts mapped to managed services (written in the README of the IaC)."""

import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Any

from nexti_core.spec.design import Design

CLOUDS = ("aws", "azure")
SERVICES = {
    "aws": {"database": "Amazon RDS", "service": "Amazon ECS on Fargate behind an Application Load Balancer",
            "secrets": "AWS Secrets Manager", "logs": "Amazon CloudWatch Logs"},
    "azure": {"database": "Azure managed database", "service": "Azure Container Apps",
              "secrets": "Azure Key Vault", "logs": "Azure Log Analytics"},
}  # fmt: skip


@dataclass(frozen=True)
class Target:
    name: str  # lowercase, letters, digits and hyphens: resource names
    cloud: str
    database: str
    tables: tuple[tuple[str, str], ...] = field(default=())  # (target table, legacy table)
    programs: tuple[str, ...] = field(default=())  # the legacy programs the service replaces


def target_of(design: Design, target: Mapping[str, Any]) -> Target | None:
    """The IaC target of a project, None when its cloud has no generator (GCP and generic Kubernetes come later)."""
    cloud = str(target.get("cloud") or "").lower()
    if cloud not in CLOUDS:
        return None
    name = re.sub(r"[^a-z0-9]+", "-", design.context.lower()).strip("-")[:20] or "app"
    database = str(target.get("database") or "postgresql").lower()
    tables = tuple((e.table, e.legacy_table or "") for e in design.entities if e.table)
    programs = tuple(sorted({u.legacy_program for u in design.use_cases if u.legacy_program}))
    return Target(name, cloud, database, tables, programs)


def readme(target: Target) -> str:
    services = SERVICES[target.cloud]
    lines = [
        f"# Infrastructure of {target.name} on {target.cloud.upper()}",
        "",
        "Generated by the NexTI platform from the approved design (ADR-0021). Validated without cloud credentials:",
        "`tofu validate` and the fitness functions of the pack. Deploying it is a decision of the customer.",
        "",
        "## Legacy concepts and the managed services that replace them",
        "",
        "| Legacy | Target |",
        "|---|---|",
    ]
    for table, legacy in target.tables:
        lines.append(f"| Table {legacy or '(new)'} | Table {table} in {services['database']} ({target.database}) |")
    for program in target.programs:
        lines.append(f"| Program {program} | The generated service on {services['service']} |")
    lines += [
        f"| Credentials in the legacy configuration | {services['secrets']} (generated, never in the code) |",
        f"| Logs of the legacy | {services['logs']} |",
        "",
        "## Use",
        "",
        "```",
        "tofu init",
        "tofu plan -var container_image=<image of the service>",
        "```",
    ]
    return "\n".join(lines) + "\n"
