"""Create infra/docker-compose/.env from .env.example, filling empty secrets with random values.

If .env already exists, only the variables it is missing are appended; existing values are never changed
(changing a database password would require recreating its volume).
"""

import re
import secrets
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SECRET_NAME = re.compile(r"(PASSWORD|_KEY|_SECRET|_SALT)$")


def secret_for(name: str) -> str:
    if name == "LANGFUSE_ENCRYPTION_KEY":
        return secrets.token_hex(32)
    return secrets.token_urlsafe(24)


def entries(text: str) -> list[tuple[str, str]]:
    """(name, value) for every variable line, ignoring comments and blank lines."""
    result = []
    for line in text.splitlines():
        name, sep, value = line.partition("=")
        if sep and not line.lstrip().startswith("#"):
            result.append((name.strip(), value))
    return result


def filled(name: str, value: str) -> str:
    return secret_for(name) if not value and SECRET_NAME.search(name) else value


def write_compose_env(target: Path) -> None:
    example = (HERE / ".env.example").read_text(encoding="utf-8")
    if not target.exists():
        lines = []
        for line in example.splitlines():
            name, sep, value = line.partition("=")
            if sep and not line.lstrip().startswith("#"):
                line = f"{name}={filled(name.strip(), value)}"
            lines.append(line)
        target.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"Wrote {target}")
        return

    current = target.read_text(encoding="utf-8")
    known = {name for name, _ in entries(current)}
    missing = [(name, value) for name, value in entries(example) if name not in known]
    if not missing:
        print(f"{target} is up to date.")
        return
    added = "".join(f"{name}={filled(name, value)}\n" for name, value in missing)
    target.write_text(current.rstrip("\n") + "\n" + added, encoding="utf-8")
    print(f"Added to {target}: {', '.join(name for name, _ in missing)}")


def write_api_env(env: dict[str, str], target: Path) -> None:
    """The API's local settings, derived from the Compose .env (regenerated on every run).

    127.0.0.1 rather than localhost: on Windows, localhost tries IPv6 first and the ports only listen on IPv4.
    """
    values = {
        "APP_ENV": "development",
        "DEV_AUTH_ENABLED": "true",
        "DATABASE_URL": (
            f"postgresql+asyncpg://platform_app:{env['PLATFORM_APP_PASSWORD']}@127.0.0.1:{env['POSTGRES_PORT']}/platform"
        ),
        "MIGRATION_DATABASE_URL": (
            f"postgresql+asyncpg://platform_owner:{env['PLATFORM_OWNER_PASSWORD']}@127.0.0.1:{env['POSTGRES_PORT']}/platform"
        ),
        "AUTHZ_RELAY_DATABASE_URL": (
            f"postgresql+asyncpg://authz_relay:{env['AUTHZ_RELAY_PASSWORD']}@127.0.0.1:{env['POSTGRES_PORT']}/platform"
        ),
        "REDIS_URL": f"redis://:{env['REDIS_PASSWORD']}@127.0.0.1:{env['REDIS_PORT']}/0",
        "KEYCLOAK_URL": f"http://127.0.0.1:{env['KEYCLOAK_PORT']}",
        "KEYCLOAK_PUBLIC_URL": f"http://localhost:{env['KEYCLOAK_PORT']}",
        "OIDC_CLIENT_SECRET": env["KC_BFF_CLIENT_SECRET"],
        "KEYCLOAK_ADMIN_CLIENT_SECRET": env["KC_ADMIN_CLIENT_SECRET"],
        "WEB_ORIGIN": env["WEB_ORIGIN"],
        "SESSION_SECRET": env["SESSION_SECRET"],
        "SECRETS_URL": f"http://127.0.0.1:{env['OPENBAO_PORT']}",
        "SECRETS_TOKEN": env["OPENBAO_DEV_ROOT_SECRET"],
        # Inputs of the projects (M2): object storage and malware scanning (ADR-0008). Local root credentials of
        # MinIO; a deployment gives the API a user limited to its bucket.
        "OBJECT_STORE_URL": f"http://127.0.0.1:{env['MINIO_API_PORT']}",
        "OBJECT_STORE_ACCESS_KEY": env["MINIO_ROOT_USER"],
        "OBJECT_STORE_SECRET_KEY": env["MINIO_ROOT_PASSWORD"],
        "MALWARE_SCANNER_HOST": "127.0.0.1",
        "MALWARE_SCANNER_PORT": env.get("CLAMAV_PORT", "3310"),
        "OPENFGA_URL": f"http://127.0.0.1:{env['OPENFGA_HTTP_PORT']}",
        "OPENFGA_API_KEY": env["OPENFGA_API_KEY"],
        # Knowledge graph (M4): Neo4j through packages/graph only.
        "GRAPH_URI": f"bolt://127.0.0.1:{env['NEO4J_BOLT_PORT']}",
        "GRAPH_USER": "neo4j",
        "GRAPH_PASSWORD": env["NEO4J_PASSWORD"],
    }
    header = "# Generated by infra/docker-compose/init_env.py from infra/docker-compose/.env. Do not edit.\n"
    target.write_text(header + "".join(f"{k}={v}\n" for k, v in values.items()), encoding="utf-8")
    print(f"Wrote {target}")


def write_worker_env(env: dict[str, str], target: Path) -> None:
    """The worker's local settings (M3): the runtime role for the database, the queue and the checkpointer; the
    object store and the secrets store for the preflight. The sandbox uses the local Docker."""
    values = {
        "APP_ENV": "development",
        "DATABASE_URL": (
            f"postgresql+asyncpg://platform_app:{env['PLATFORM_APP_PASSWORD']}@127.0.0.1:{env['POSTGRES_PORT']}/platform"
        ),
        "SECRETS_URL": f"http://127.0.0.1:{env['OPENBAO_PORT']}",
        "SECRETS_TOKEN": env["OPENBAO_DEV_ROOT_SECRET"],
        "OBJECT_STORE_URL": f"http://127.0.0.1:{env['MINIO_API_PORT']}",
        "OBJECT_STORE_ACCESS_KEY": env["MINIO_ROOT_USER"],
        "OBJECT_STORE_SECRET_KEY": env["MINIO_ROOT_PASSWORD"],
        "GRAPH_URI": f"bolt://127.0.0.1:{env['NEO4J_BOLT_PORT']}",
        "GRAPH_USER": "neo4j",
        "GRAPH_PASSWORD": env["NEO4J_PASSWORD"],
    }
    header = "# Generated by infra/docker-compose/init_env.py from infra/docker-compose/.env. Do not edit.\n"
    target.write_text(header + "".join(f"{k}={v}\n" for k, v in values.items()), encoding="utf-8")
    print(f"Wrote {target}")


def main() -> int:
    compose_env = HERE / ".env"
    write_compose_env(compose_env)
    env = dict(entries(compose_env.read_text(encoding="utf-8")))
    write_api_env(env, HERE.parents[1] / "apps" / "api" / ".env")
    write_worker_env(env, HERE.parents[1] / "apps" / "worker" / ".env")
    return 0


if __name__ == "__main__":
    sys.exit(main())
