"""The strangler fig cutover plan (spec 6.3, ADR-0023), computed from the approved design: each legacy program and the
route of the service that replaces it, the order of the cutover by domain, and the anti-corruption layer where the
new service still calls legacy programs. Plain files the customer's team follows and their gateway can read."""

import re

from nexti_core.spec.design import Design, UseCase

PLAN = "docs/cutover/PLAN.md"
ROUTING = "docs/cutover/routing.yaml"


def kebab(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def route(design: Design, use_case: UseCase) -> str:
    """The path the packs give the use case's endpoint (`/api/<context>/<path>`)."""
    return f"/api/{design.context}{use_case.path or '/' + kebab(use_case.name)}"


def plan(design: Design) -> dict[str, str]:
    routes = [(u, route(design, u)) for u in design.use_cases]
    legacy_ports = [p for p in design.ports if p.legacy_program]
    lines = [
        f"# Cutover plan: {design.context}",
        "",
        "Generated by the NexTI platform from the approved design (spec 6.3, ADR-0023). The legacy keeps running while",
        "the new service takes its traffic one program at a time (strangler fig).",
        "",
        "## Routes",
        "",
        "| Legacy program | New endpoint | Rules |",
        "|---|---|---|",
    ]
    lines += [
        f"| {u.legacy_program or '(new)'} | `{u.http_method} {path}` | {', '.join(u.rules)} |" for u, path in routes
    ]
    lines += [
        "",
        "## Steps per program",
        "",
        "1. Deploy the new service next to the legacy; the gateway keeps every call on the legacy.",
        "2. **Shadow:** the gateway copies the calls to the new endpoint and compares the answers (the golden",
        "   master of the verification is the reference); the answers to the users still come from the legacy.",
        "3. **Primary:** the gateway sends the calls to the new endpoint; the legacy stays as fallback for one cycle.",
        "4. **Retire:** the legacy program stops receiving calls and is archived.",
        "",
        "`routing.yaml` lists every route with its mode (`legacy`, `shadow`, `primary`); the team changes the mode,",
        "program by program, in its gateway.",
    ]
    if legacy_ports:
        lines += ["", "## Anti-corruption layer", "",
                  "The new service still depends on these legacy programs through ports; their adapters translate the",
                  "legacy model and stay until each program is migrated:", ""]  # fmt: skip
        lines += [f"- `{p.name}` → legacy `{p.legacy_program}`" for p in legacy_ports]
    routing = [f"# Strangler fig routes of {design.context} (spec 6.3). mode: legacy | shadow | primary", "routes:"]
    for u, path in routes:
        routing += [f"  - legacy: {u.legacy_program or 'none'}", f"    method: {u.http_method}", f"    path: {path}",
                    f"    service: {u.name}", "    mode: legacy"]  # fmt: skip
    return {PLAN: "\n".join(lines) + "\n", ROUTING: "\n".join(routing) + "\n"}
